### PR TITLE
Upgrade for Agda 2.5.1.2

### PR DESCRIPTION
**Pull request by Blaisorblade**
Update to Agda 2.5.1.2. Not urgent in any way—I needed it myself, so I'm sharing.

### CODE REVIEW

**Comment by sstucki** [comment]
Thanks for the PR @Blaisorblade, I've been meaning to do this for a while :-)

The PR LGTM, except that commit b917d0b should not requires an `AllExtras` module. The respective properties are in the `Data.Vec.All.Properties` module of the standard library now. Would you mind changing the commit accordingly? O/w I can do it myself later.

**Comment by Blaisorblade** [comment]
Revised and force-pushed. Ended up picking a few more nits, hope you don't dislike them.

**Comment by sstucki** [comment]
Thanks @Blaisorblade!

Actually, I just realized [README.agda](https://github.com/Blaisorblade/pts-agda/blob/33898ec88f0ea4d14288db0ed3ebc26d4194c14b/src/README.agda#L47) still contains imports for `SymmetricClosure` and `EquivalenceClosure`. Would you min removing them?

**Comment by Blaisorblade** [comment]
Done!

**Comment by sstucki** [comment]
LGTM now, merged. Thanks again!

**Pull request merged**
